In [1]:
import numpy as np
import pandas as pd

In [2]:
x0 = np.load('X0_ml100k.npy')
x0

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.]])

In [3]:
x0.shape

(78799, 48)

In [4]:
x1 = np.load('X1_ml100k.npy')
x1

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [5]:
x1.shape

(21201, 48)

In [6]:
from ucimlrepo import fetch_ucirepo
wine_quality = fetch_ucirepo(id=186)

In [7]:
X = wine_quality.data.features
X

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
0               7.4              0.70         0.00             1.9      0.076   
1               7.8              0.88         0.00             2.6      0.098   
2               7.8              0.76         0.04             2.3      0.092   
3              11.2              0.28         0.56             1.9      0.075   
4               7.4              0.70         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
6492            6.2              0.21         0.29             1.6      0.039   
6493            6.6              0.32         0.36             8.0      0.047   
6494            6.5              0.24         0.19             1.2      0.041   
6495            5.5              0.29         0.30             1.1      0.022   
6496            6.0              0.21         0.38             0.8      0.020   

      free_sulfur_dioxide  total_sulfur_dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
6492                 24.0                  92.0  0.99114  3.27       0.50   
6493                 57.0                 168.0  0.99490  3.15       0.46   
6494                 30.0                 111.0  0.99254  2.99       0.46   
6495                 20.0                 110.0  0.98869  3.34       0.38   
6496                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  
0         9.4  
1         9.8  
2         9.8  
3         9.8  
4         9.4  
...       ...  
6492     11.2  
6493      9.6  
6494      9.4  
6495     12.8  
6496     11.8  

[6497 rows x 11 columns]

In [8]:
Y = wine_quality.data.targets
Y

quality
0           5
1           5
2           5
3           6
4           5
...       ...
6492        6
6493        5
6494        6
6495        7
6496        6

[6497 rows x 1 columns]

In [9]:
np.unique(Y)

array([3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [12]:
pd.concat((X, Y), axis=1)

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
0               7.4              0.70         0.00             1.9      0.076   
1               7.8              0.88         0.00             2.6      0.098   
2               7.8              0.76         0.04             2.3      0.092   
3              11.2              0.28         0.56             1.9      0.075   
4               7.4              0.70         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
6492            6.2              0.21         0.29             1.6      0.039   
6493            6.6              0.32         0.36             8.0      0.047   
6494            6.5              0.24         0.19             1.2      0.041   
6495            5.5              0.29         0.30             1.1      0.022   
6496            6.0              0.21         0.38             0.8      0.020   

      free_sulfur_dioxide  total_sulfur_dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
6492                 24.0                  92.0  0.99114  3.27       0.50   
6493                 57.0                 168.0  0.99490  3.15       0.46   
6494                 30.0                 111.0  0.99254  2.99       0.46   
6495                 20.0                 110.0  0.98869  3.34       0.38   
6496                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
6492     11.2        6  
6493      9.6        5  
6494      9.4        6  
6495     12.8        7  
6496     11.8        6  

[6497 rows x 12 columns]

In [4]:
from os.path import dirname, abspath
dataset_path = dirname(dirname(abspath('')))
data = pd.read_csv(dataset_path+"/ml-100k/raw/u.data", sep ="\t", header=None, names = ["user_id", "movie_id","rating", "timestamp"])
data = data.drop(["timestamp"], axis = 1)

# reward criteria is set here
data["reward"] = np.where(data["rating"] < 5,0,1)
data.pop("rating")
data = data.reset_index(drop = True)

data_array = data.to_numpy()

movieY = data_array[:,2]
movieY

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [5]:
movieY.shape

(100000,)

In [6]:
np.unique(movieY)

array([0, 1], dtype=int64)

In [7]:
reward0_idx = np.where(movieY == 0)[0]
reward1_idx = np.where(movieY == 1)[0]

In [8]:
print(reward0_idx)
print(reward0_idx.shape)

[    0     1     2 ... 99997 99998 99999]
(78799,)


In [9]:
print(reward1_idx)
print(reward1_idx.shape)

[    7    11    12 ... 99963 99978 99996]
(21201,)


In [14]:
%pip install ucimlrepo
from ucimlrepo import fetch_ucirepo
dataset = fetch_ucirepo(id=186)

np.unique(dataset.data.targets, return_counts=True)

Note: you may need to restart the kernel to use updated packages.


(array([3, 4, 5, 6, 7, 8, 9], dtype=int64),
 array([  30,  216, 2138, 2836, 1079,  193,    5], dtype=int64))